---
- name: Create {{ nextcloudpi_compose_dir }} if it does not exist
  file:
    path: "{{ nextcloudpi_compose_dir }}"
    state: directory
    mode: '0755'

- name: Create {{ nextcloudpi_data_dir }} if it does not exist
  become: yes
  become_user: root
  file:
    path: "{{ nextcloudpi_data_dir }}"
    state: directory

- name: install autofs
  become: yes
  become_user: root
  pacman:
    name: autofs
    state: present

- name: install cifs-utils
  become: yes
  become_user: root
  pacman:
    name: cifs-utils
    state: present

- name: create {{ nextcloudpi_backup_dir }} if it does not exist
  become: yes
  become_user: root
  file:
    path: "{{ nextcloudpi_backup_dir }}"
    state: directory

- name: create auto.backup
  become: yes
  become_user: root
  copy:
    dest: "/etc/autofs/auto.backup"
    content: |
      nextcloud -fstype=cifs,username={{ backup_remote_location_user }},password={{ backup_remote_location_user_password }},file_mode=0644,dir_mode=0755 :{{ backup_remote_location }}

- name: add auto.backup to auto.master
  become: yes
  become_user: root
  lineinfile:
    line: "{{ nextcloudpi_backup_dir }} /etc/autofs/auto.backup --timeout 60 --browse"
    dest: "/etc/autofs/auto.master"

- name: enable autofs
  become: yes
  become_user: root
  service:
    name: autofs
    enabled: yes
    state: started

- name: copy docker-compose.yml
  template:
    src: docker-compose.yml
    dest: "{{ nextcloudpi_compose_dir }}/docker-compose.yml"

- name: start nextcloudpi
  shell: docker-compose up --build -d
  args:
    chdir: "{{ nextcloudpi_compose_dir }}"