---
- hosts: all
  any_errors_fatal: true
  roles:
    - base-arch-config

- hosts: all
  any_errors_fatal: true
  roles:
    - reboot 

- hosts: all
  any_errors_fatal: true
  roles:
    - pihole
  vars_prompt:
    - name: "webpassword"
      prompt: "Define your pihole webpassword (for Login)"
      private: yes
      confirm: yes

- hosts: all
  any_errors_fatal: true
  roles:
    - nextcloudpi
  vars_prompt:
    - name: "nextcloudpi_usb_stick"
      prompt: "Path to the USB Stick"
      default: "/dev/sda1"
      private: no
      confirm: yes