---
- hosts: all
  any_errors_fatal: true
  roles:
    - base-arch-config

- hosts: all
  any_errors_fatal: true
  roles:
    - reboot 

- hosts: all
  any_errors_fatal: true
  roles:
    - pihole
  vars_prompt:
    - name: "webpassword"
      prompt: "Define your pihole webpassword (for Login)"
      private: yes

- hosts: all
  any_errors_fatal: true
  roles:
    - nextcloudpi
