---
- hosts: all
  any_errors_fatal: true
  roles:
    - base-arch-config

- hosts: all
  any_errors_fatal: true
  roles:
    - mount-usb

- hosts: all
  any_errors_fatal: true
  roles:
    - reboot 

- hosts: all
  any_errors_fatal: true
  roles:
    - monitoring
  vars_prompt:
    - name: "grafana_admin_user"
      prompt: "Grafana Admin User"
      private: no
    - name: "grafana_admin_password"
      prompt: "Grafana Admin Password"
      private: yes
      confirm: yes
    - name: "telegram_bot_token"
      prompt: "Telegram Bot Token"
      private: no
    - name: "telegram_chat_id"
      prompt: "Telegram Chat Id"
      private: no

- hosts: all
  any_errors_fatal: true
  roles:
    - pihole
  vars_prompt:
    - name: "webpassword"
      prompt: "Define your pihole webpassword (for Login)"
      private: yes
      confirm: yes
    - name: "conditional_forwarding_ip"
      prompt: "Set the IP of the local network router"
      default: "192.168.178.1"
      private: no
    - name: "conditional_forwarding_domain"
      prompt: "Set the reverse DNS of the local network router"
      default: "fritz.box"
      private: no

# - hosts: all
#   any_errors_fatal: true
#   roles:
#     - nextcloudpi
#   vars_prompt:
#     - name: "backup_remote_location"
#       prompt: "Remote Location (Samba location)"
#       default: "//Datengrab/backup/Nextcloud"
#       private: no
#     - name: "backup_remote_location_user"
#       prompt: "Remote User (needed to access Backups)"
#       default: "backup"
#       private: no
#     - name: "backup_remote_location_user_password"
#       prompt: "Remote User Password"
#       private: yes
#       confirm: yes

- hosts: all
  any_errors_fatal: true
  roles:
    - nextcloud
  vars_prompt:
    - name: "duckdns_subdomain"
      prompt: "Duckdns Sub Domain (like 'nextcloud')"
      private: no
    - name: "duckdns_token"
      prompt: "Duckdns Token"
      private: no
    - name: "mysql_password"
      prompt: "Set the MYSQL_PASSWORD"
      private: yes
      confirm: yes
    - name: "mysql_root_password"
      prompt: "Set the MYSQL_ROOT_PASSWORD"
      private: yes
      confirm: yes
    - name: "traefik_challenge_email"
      prompt: "Set the certificate challenge E-Mail"
      private: no
    - name: "backup_remote_location"
      prompt: "Remote Location (Samba location)"
      default: "//Datengrab/backup/Nextcloud"
      private: no
    - name: "backup_remote_location_user"
      prompt: "Remote User (needed to access Backups)"
      default: "backup"
      private: no
    - name: "backup_remote_location_user_password"
      prompt: "Remote User Password"
      private: yes
      confirm: yes

- hosts: all
  any_errors_fatal: true
  roles:
    - samba
  vars_prompt:
    - name: "samba_user"
      prompt: "Samba User"
      default: "samba"
      private: no
    - name: "samba_user_password"
      prompt: "Samba User Password"
      private: yes
      confirm: yes

- hosts: all
  any_errors_fatal: true
  roles:
    - jdownloader
  vars_prompt:
    - name: "jdownloader_user"
      prompt: "MyJdownloader User"
      private: no
    - name: "jdownloader_user_password"
      prompt: "MyJdownloader User Password"
      private: yes
      confirm: yes

- hosts: all
  any_errors_fatal: true
  roles:
    - logitechmediaserver
  vars_prompt:
    - name: "music_remote_location"
      prompt: "Remote Location (Samba location)"
      default: "//Datengrab/Daten/Musik/sortiert"
      private: no
    - name: "music_remote_location_user"
      prompt: "Remote User (needed to access Backups)"
      default: "media"
      private: no
    - name: "music_remote_location_user_password"
      prompt: "Remote User Password"
      private: yes
      confirm: yes

# - hosts: all
#   any_errors_fatal: true
#   roles:
#     - pyload