version: "3"

services:
  samba:
    container_name: samba
    image: dperson/samba:latest
    environment:
      TZ: 'Europe/Berlin'
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    tmpfs:
      - /tmp
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - {{ scan_data_dir }}:{{ scan_data_dir }}:z
    command: '-s "scans;{{ scan_data_dir }};yes;no;no;{{ samba_user }}" -u "{{ samba_user }};{{ samba_user_password }}" -p -g "server min protocol = NT1"' # HP Scanner needs SMB1 (== NT1)