---
- name: enable systemd-resolved
  become: yes
  become_user: root
  service:
    name: systemd-resolved.service
    enabled: yes 
    state: started

- name: Ensures /etc/systemd/resolved.conf.d/ dir exists
  become: yes
  become_user: root
  file: 
    path: /etc/systemd/resolved.conf.d/ 
    state: directory

- name: copy resolv.conf.head
  become: yes
  become_user: root
  template:
    src: resolv.conf.head
    dest: /etc/resolv.conf.head