---
- name: create aur_builder
  become: yes
  become_user: root
  user:
    name: aur_builder
    group: wheel

- name: setup sudoers file for aur_builder
  become: yes
  become_user: root
  lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    validate: 'visudo -cf %s'

- name: install yay (from manjaro repositories)
  become: yes
  become_user: root
  pacman:
      name: yay
      state: present