version: "3"

services:
  nextcloudpi:
    container_name: nextcloudpi
    image: ownyourbits/nextcloudpi:latest
    command: "192.168.178.20"
    ports:
      - "443:443"
      - "4443:4443"
      - "80:80"
    volumes:
       - './ncdata/:/data'
    restart: unless-stopped