version: "3"

services:
  nextcloudpi:
    container_name: nextcloudpi
    image: ownyourbits/nextcloudpi:latest
    command: "{{ ansible_default_ipv4.address }}"
    ports:
      - "443:443"
      - "4443:4443"
      - "80:80"
    volumes:
       - '{{ nextcloudpi_usb_mount_dir }}/data/:/data'
       - '{{ nextcloudpi_backup_dir }}/nextcloud/:/backups'
    restart: unless-stopped