---
- name: Create {{ usb_mount_dir }} if it does not exist
  become: yes
  become_user: root
  file:
    path: "{{ usb_mount_dir }}"
    state: directory

- name: Mount {{ usb_stick }} to {{ usb_mount_dir }}
  become: yes
  become_user: root
  mount:
    path: "{{ usb_mount_dir }}"
    src: "{{ usb_stick }}"
    fstype: ext4
    opts: defaults,auto,nofail,exec,noatime
    state: mounted

