version: "3"

services:
  jdownloader:
    container_name: jdownloader
    image: jaymoulin/jdownloader:latest
    restart: always
    user: {{ download_dir.stat.uid }}:{{ download_dir.stat.gid }}
    volumes:
      - {{ jdownloader_config_dir }}:/opt/JDownloader/cfg
      - {{ jdownloader_logs_dir }}:/opt/JDownloader/logs
      - {{ jdownloader_download_dir }}:/Downloads:z
      - /etc/localtime:/etc/localtime:ro
    environment: 
      MYJD_USER: '{{ jdownloader_user }}'
      MYJD_PASSWORD: '{{ jdownloader_user_password }}'
      MYJD_DEVICE_NAME: Insomnia
      XDG_DOWNLOAD_DIR: /Downloads
    ports:
      - 3129:3129