# The leds can be annoying. You can disable them.
# The PWR (a red LED) and ACT (a green LED) of the RaspberryPi. Possible variables:
# 'true' to disable the led or any other value like 'false' to skip this role to disable the led.
pwr_led_disabled: true
act_led_disabled: false

# Specify the user default shell you want to use. Possible variables:
# - 'zsh' => it will also install antigen and some plugins.
# - 'bash' => will also install bash-completion
# - 'none' => will skip the shell setup and uses the default setting.
shell: zsh